# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NOVO_SERVICO.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

#caixa de texto Cliente: lineEdit
from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3

class Ui_NOVO_SERVICO(object):
    def messagebox(self,title,message):
        mess=QtWidgets.QMessageBox()
        mess.setWindowTitle(title)
        mess.setText(mes)
        mess.setStandardButtons(QtWidgets,QMessageBox.Ok)
        mess.exec_()
    def add_serv(self):
        NOME_CLIENTE = self.lineEdit.text()
        LOTACAO_CLIENTE = self.lineEdit_2.text()
        RAMAL_CLIENTE = self.lineEdit_4.text()
        conexao=sqlite3.connect("TOMO_TESTE.db")
        cur=conexao.cursor()
        query=("INSERT INTO CLIENTE (NOME_CLIENTE,LOTACAO_CLIENTE,RAMAL_CLIENTE) VALUES (?, ?, ?)")
        cur.execute(query)
        conexao.commit()
        cur.close()
        conexao.close()
        
    def setupUi(self, NOVO_SERVICO):
        NOVO_SERVICO.setObjectName("NOVO_SERVICO")
        NOVO_SERVICO.resize(1031, 990)
        self.buttonBox = QtWidgets.QDialogButtonBox(NOVO_SERVICO)
        self.buttonBox.setGeometry(QtCore.QRect(450, 870, 161, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(NOVO_SERVICO)
        self.label.setGeometry(QtCore.QRect(170, 90, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setMidLineWidth(0)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setScaledContents(False)
        self.label.setWordWrap(False)
        self.label.setOpenExternalLinks(False)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(NOVO_SERVICO)
        self.label_2.setGeometry(QtCore.QRect(70, 130, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_2.setMidLineWidth(0)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setScaledContents(False)
        self.label_2.setWordWrap(False)
        self.label_2.setOpenExternalLinks(False)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(NOVO_SERVICO)
        self.label_3.setGeometry(QtCore.QRect(150, 210, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_3.setMidLineWidth(0)
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setScaledContents(False)
        self.label_3.setWordWrap(False)
        self.label_3.setOpenExternalLinks(False)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(NOVO_SERVICO)
        self.label_4.setGeometry(QtCore.QRect(100, 170, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_4.setMidLineWidth(0)
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setScaledContents(False)
        self.label_4.setWordWrap(False)
        self.label_4.setOpenExternalLinks(False)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(NOVO_SERVICO)
        self.label_5.setGeometry(QtCore.QRect(70, 533, 151, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_5.setFont(font)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_5.setMidLineWidth(0)
        self.label_5.setTextFormat(QtCore.Qt.AutoText)
        self.label_5.setScaledContents(False)
        self.label_5.setWordWrap(False)
        self.label_5.setOpenExternalLinks(False)
        self.label_5.setObjectName("label_5")
        self.lineEdit = QtWidgets.QLineEdit(NOVO_SERVICO)
        self.lineEdit.setGeometry(QtCore.QRect(290, 100, 411, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(NOVO_SERVICO)
        self.lineEdit_2.setGeometry(QtCore.QRect(290, 140, 411, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(NOVO_SERVICO)
        self.lineEdit_3.setGeometry(QtCore.QRect(290, 220, 191, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(NOVO_SERVICO)
        self.lineEdit_4.setGeometry(QtCore.QRect(290, 180, 191, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_6 = QtWidgets.QLineEdit(NOVO_SERVICO)
        self.lineEdit_6.setGeometry(QtCore.QRect(50, 550, 191, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_10 = QtWidgets.QLabel(NOVO_SERVICO)
        self.label_10.setGeometry(QtCore.QRect(100, 250, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_10.setFont(font)
        self.label_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_10.setMidLineWidth(0)
        self.label_10.setTextFormat(QtCore.Qt.AutoText)
        self.label_10.setScaledContents(False)
        self.label_10.setWordWrap(False)
        self.label_10.setOpenExternalLinks(False)
        self.label_10.setObjectName("label_10")
        self.groupBox = QtWidgets.QGroupBox(NOVO_SERVICO)
        self.groupBox.setGeometry(QtCore.QRect(30, 440, 891, 341))
        self.groupBox.setObjectName("groupBox")
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_2.setGeometry(QtCore.QRect(270, 109, 131, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.comboBox_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_2.setDuplicatesEnabled(False)
        self.comboBox_2.setFrame(True)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.setItemText(0, "--")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(270, 90, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_8.setFont(font)
        self.label_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_8.setMidLineWidth(0)
        self.label_8.setTextFormat(QtCore.Qt.AutoText)
        self.label_8.setScaledContents(False)
        self.label_8.setWordWrap(False)
        self.label_8.setOpenExternalLinks(False)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(440, 92, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_9.setFont(font)
        self.label_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_9.setMidLineWidth(0)
        self.label_9.setTextFormat(QtCore.Qt.AutoText)
        self.label_9.setScaledContents(False)
        self.label_9.setWordWrap(False)
        self.label_9.setOpenExternalLinks(False)
        self.label_9.setObjectName("label_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_10.setGeometry(QtCore.QRect(410, 110, 221, 20))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(220, 93, 41, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_11.setFont(font)
        self.label_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_11.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_11.setMidLineWidth(0)
        self.label_11.setTextFormat(QtCore.Qt.AutoText)
        self.label_11.setScaledContents(False)
        self.label_11.setWordWrap(False)
        self.label_11.setOpenExternalLinks(False)
        self.label_11.setObjectName("label_11")
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_3.setGeometry(QtCore.QRect(220, 110, 31, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.comboBox_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_3.setDuplicatesEnabled(False)
        self.comboBox_3.setFrame(True)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.setItemText(0, "--")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(790, 106, 41, 26))
        self.pushButton.setObjectName("pushButton")
        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_4.setGeometry(QtCore.QRect(650, 109, 121, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.comboBox_4.setFont(font)
        self.comboBox_4.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.comboBox_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_4.setDuplicatesEnabled(False)
        self.comboBox_4.setFrame(True)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.setItemText(0, "--")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(660, 90, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_12.setFont(font)
        self.label_12.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_12.setMidLineWidth(0)
        self.label_12.setTextFormat(QtCore.Qt.AutoText)
        self.label_12.setScaledContents(False)
        self.label_12.setWordWrap(False)
        self.label_12.setOpenExternalLinks(False)
        self.label_12.setObjectName("label_12")
        self.comboBox_5 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_5.setGeometry(QtCore.QRect(20, 200, 191, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.comboBox_5.setFont(font)
        self.comboBox_5.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.comboBox_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_5.setDuplicatesEnabled(False)
        self.comboBox_5.setFrame(True)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.setItemText(0, "--")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setGeometry(QtCore.QRect(20, 170, 241, 20))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_13.setFont(font)
        self.label_13.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_13.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_13.setMidLineWidth(0)
        self.label_13.setTextFormat(QtCore.Qt.AutoText)
        self.label_13.setScaledContents(False)
        self.label_13.setWordWrap(False)
        self.label_13.setOpenExternalLinks(False)
        self.label_13.setObjectName("label_13")
        self.checkBox = QtWidgets.QCheckBox(NOVO_SERVICO)
        self.checkBox.setGeometry(QtCore.QRect(490, 300, 16, 17))
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.label_6 = QtWidgets.QLabel(NOVO_SERVICO)
        self.label_6.setGeometry(QtCore.QRect(390, 288, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_6.setFont(font)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_6.setMidLineWidth(0)
        self.label_6.setTextFormat(QtCore.Qt.AutoText)
        self.label_6.setScaledContents(False)
        self.label_6.setWordWrap(False)
        self.label_6.setOpenExternalLinks(False)
        self.label_6.setObjectName("label_6")
        self.lineEdit_5 = QtWidgets.QLineEdit(NOVO_SERVICO)
        self.lineEdit_5.setGeometry(QtCore.QRect(290, 340, 191, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_7 = QtWidgets.QLabel(NOVO_SERVICO)
        self.label_7.setGeometry(QtCore.QRect(100, 340, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_7.setFont(font)
        self.label_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_7.setMidLineWidth(0)
        self.label_7.setTextFormat(QtCore.Qt.AutoText)
        self.label_7.setScaledContents(False)
        self.label_7.setWordWrap(False)
        self.label_7.setOpenExternalLinks(False)
        self.label_7.setObjectName("label_7")
        self.lineEdit_7 = QtWidgets.QLineEdit(NOVO_SERVICO)
        self.lineEdit_7.setGeometry(QtCore.QRect(290, 260, 191, 20))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_14 = QtWidgets.QLabel(NOVO_SERVICO)
        self.label_14.setGeometry(QtCore.QRect(150, 290, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_14.setFont(font)
        self.label_14.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_14.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_14.setMidLineWidth(0)
        self.label_14.setTextFormat(QtCore.Qt.AutoText)
        self.label_14.setScaledContents(False)
        self.label_14.setWordWrap(False)
        self.label_14.setOpenExternalLinks(False)
        self.label_14.setObjectName("label_14")
        self.comboBox_6 = QtWidgets.QComboBox(NOVO_SERVICO)
        self.comboBox_6.setGeometry(QtCore.QRect(290, 300, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.comboBox_6.setFont(font)
        self.comboBox_6.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.comboBox_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_6.setDuplicatesEnabled(False)
        self.comboBox_6.setFrame(True)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.setItemText(0, "--")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.groupBox.raise_()
        self.buttonBox.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.lineEdit.raise_()
        self.lineEdit_2.raise_()
        self.lineEdit_3.raise_()
        self.lineEdit_4.raise_()
        self.lineEdit_6.raise_()
        self.label_10.raise_()
        self.checkBox.raise_()
        self.label_6.raise_()
        self.lineEdit_5.raise_()
        self.label_7.raise_()
        self.lineEdit_7.raise_()
        self.label_14.raise_()
        self.comboBox_6.raise_()

        self.retranslateUi(NOVO_SERVICO)
        self.buttonBox.accepted.connect(NOVO_SERVICO.accept)
        self.buttonBox.rejected.connect(NOVO_SERVICO.reject)
        QtCore.QMetaObject.connectSlotsByName(NOVO_SERVICO)

    def retranslateUi(self, NOVO_SERVICO):
        _translate = QtCore.QCoreApplication.translate
        NOVO_SERVICO.setWindowTitle(_translate("NOVO_SERVICO", "ADD_SERVICE"))
        self.label.setText(_translate("NOVO_SERVICO", "Cliente :"))
        self.label_2.setText(_translate("NOVO_SERVICO", "Lotação do Cliente :"))
        self.label_3.setText(_translate("NOVO_SERVICO", "Número SAS:"))
        self.label_4.setText(_translate("NOVO_SERVICO", "Ramal de Contato:"))
        self.label_5.setText(_translate("NOVO_SERVICO", "Nome da Amostra:"))
        self.label_10.setText(_translate("NOVO_SERVICO", "Diagrama de Rede:"))
        self.groupBox.setTitle(_translate("NOVO_SERVICO", "Adiciona Amostra"))
        self.comboBox_2.setItemText(1, _translate("NOVO_SERVICO", "Não-Geológica"))
        self.comboBox_2.setItemText(2, _translate("NOVO_SERVICO", "POÇO"))
        self.comboBox_2.setItemText(3, _translate("NOVO_SERVICO", "AFLORAMENTO"))
        self.label_8.setText(_translate("NOVO_SERVICO", "Tipo da Origem:"))
        self.label_9.setText(_translate("NOVO_SERVICO", "Nome da Origem:"))
        self.label_11.setText(_translate("NOVO_SERVICO", "Tipo:"))
        self.comboBox_3.setItemText(1, _translate("NOVO_SERVICO", "P"))
        self.comboBox_3.setItemText(2, _translate("NOVO_SERVICO", "AF"))
        self.comboBox_3.setItemText(3, _translate("NOVO_SERVICO", "AL"))
        self.pushButton.setText(_translate("NOVO_SERVICO", "Add"))
        self.comboBox_4.setItemText(1, _translate("NOVO_SERVICO", "MICRO ALTA"))
        self.comboBox_4.setItemText(2, _translate("NOVO_SERVICO", "MICRO ROTINA"))
        self.comboBox_4.setItemText(3, _translate("NOVO_SERVICO", "MICRO ESPECIAL"))
        self.comboBox_4.setItemText(4, _translate("NOVO_SERVICO", "ROCHA DIGITAL"))
        self.comboBox_4.setItemText(5, _translate("NOVO_SERVICO", "TOMO TESTO"))
        self.comboBox_4.setItemText(6, _translate("NOVO_SERVICO", "TOMO WC"))
        self.comboBox_4.setItemText(7, _translate("NOVO_SERVICO", "TOMO GERAL"))
        self.label_12.setText(_translate("NOVO_SERVICO", "Modalidade:"))
        self.comboBox_5.setItemText(1, _translate("NOVO_SERVICO", "Não (Só Processamento)"))
        self.comboBox_5.setItemText(2, _translate("NOVO_SERVICO", "SIM"))
        self.label_13.setText(_translate("NOVO_SERVICO", "Amostra(s) no Laboratório?"))
        self.label_6.setText(_translate("NOVO_SERVICO", "Parceria?"))
        self.label_7.setText(_translate("NOVO_SERVICO", "Empresa Parceira:"))
        self.label_14.setText(_translate("NOVO_SERVICO", "Finalidade:"))
        self.comboBox_6.setItemText(1, _translate("NOVO_SERVICO", "SERVIÇO"))
        self.comboBox_6.setItemText(2, _translate("NOVO_SERVICO", "PROJETO"))
        self.buttonBox.clicked.connect(self.add_serv)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NOVO_SERVICO = QtWidgets.QDialog()
    ui = Ui_NOVO_SERVICO()
    ui.setupUi(NOVO_SERVICO)
    NOVO_SERVICO.show()
    sys.exit(app.exec_())

